"""Real STM32 build / flash / device-detection.

Shells out to PlatformIO (build + flash) and OpenOCD (ST-Link detection over SWD)
against the on-disk project workspace that GitManager already materializes at
``backend/data/workspaces/<project_id>/``. Mirrors the ``subprocess.run`` pattern
in :mod:`agent.git_manager`.

Toolchain resolution favors an app-owned PlatformIO/OpenOCD so the shipped app
needs no manual installs:
  - PlatformIO: ``$PIO_BIN`` -> app venv ``data/penv/bin/pio`` -> ``~/.platformio``.
    If none exist, :func:`ensure_platformio` auto-provisions one into ``data/penv``.
  - OpenOCD: ``$OPENOCD_BIN`` -> vendored ``vendor/openocd/<platform>/bin/openocd``
    -> ``openocd`` on PATH.

Default target is the STM32F103C8 Blue Pill flashed via ST-Link.
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path
import re

from schemas import BuildResult, DeviceStatus, FlashResult
from boards.detector import candidates_for_family, detect_from_workspace
from boards.registry import registry

BACKEND_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BACKEND_DIR / "data"
WORKSPACES_DIR = DATA_DIR / "workspaces"
PENV_DIR = DATA_DIR / "penv"
VENDOR_DIR = BACKEND_DIR / "vendor"


DEFAULT_BOARD = registry.default().id
DEFAULT_BOARD_LABEL = registry.default().label

# Bound the time any single shelled command may run so a stuck probe/build can't
# hang a request forever.
DETECT_TIMEOUT_S = 15
BUILD_TIMEOUT_S = 600
FLASH_TIMEOUT_S = 180

_PLATFORMIO_INI_TEMPLATE = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = ststm32
board = {board}
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
"""

_PLATFORMIO_INI_TEMPLATE_AVR = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = atmelavr
board = {board}
framework = arduino
upload_speed = {upload_speed}
"""

_PLATFORMIO_INI_TEMPLATE_ESP = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = {espressif_platform}
board = {board}
framework = arduino
upload_speed = {upload_speed}
"""

_PLATFORMIO_INI_TEMPLATE_ESPIDF = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = espressif32
board = {board}
framework = espidf
upload_speed = {upload_speed}
monitor_speed = 115200
"""

_PLATFORMIO_INI_TEMPLATE_SAMD = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = atmelsam
board = {board}
framework = arduino
upload_speed = {upload_speed}
"""

_PLATFORMIO_INI_TEMPLATE_ARDUINO_GENERIC = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = {platform}
board = {board}
framework = arduino
upload_speed = {upload_speed}
"""


# ---------------------------------------------------------------------------
# Toolchain resolution
# ---------------------------------------------------------------------------


def _platform_slug() -> str:
    if sys.platform.startswith("win"):
        return "windows"
    if sys.platform == "darwin":
        return "macos"
    return "linux"


def _pio_candidates() -> list[Path]:
    exe = "pio.exe" if sys.platform.startswith("win") else "pio"
    bin_dir = "Scripts" if sys.platform.startswith("win") else "bin"
    return [
        PENV_DIR / bin_dir / exe,
        Path.home() / ".platformio" / "penv" / bin_dir / exe,
    ]


def pio_bin() -> str | None:
    """Resolve an existing PlatformIO executable, or None if not installed yet."""
    override = os.environ.get("PIO_BIN")
    if override and Path(override).exists():
        return override
    for cand in _pio_candidates():
        if cand.exists():
            return str(cand)
    return None


def openocd_bin() -> str:
    """Resolve OpenOCD: env override -> vendored -> PATH (`openocd`)."""
    override = os.environ.get("OPENOCD_BIN")
    if override:
        return override
    exe = "openocd.exe" if sys.platform.startswith("win") else "openocd"
    vendored = VENDOR_DIR / "openocd" / _platform_slug() / "bin" / exe
    if vendored.exists():
        return str(vendored)
    return "openocd"


def ensure_platformio() -> str:
    """Return a usable `pio` path, provisioning an app-owned core if needed.

    Creates ``data/penv`` and ``pip install platformio`` into it on first use so
    the end user never installs anything manually. Raises RuntimeError on failure.
    """
    found = pio_bin()
    if found:
        return found

    bin_dir = "Scripts" if sys.platform.startswith("win") else "bin"
    exe = "pio.exe" if sys.platform.startswith("win") else "pio"
    PENV_DIR.parent.mkdir(parents=True, exist_ok=True)

    # Build an isolated venv and install PlatformIO into it.
    venv = subprocess.run(
        [sys.executable, "-m", "venv", str(PENV_DIR)],
        capture_output=True, text=True,
    )
    if venv.returncode != 0:
        raise RuntimeError(f"Could not create PlatformIO venv:\n{venv.stderr}")

    py = PENV_DIR / bin_dir / ("python.exe" if sys.platform.startswith("win") else "python")
    install = subprocess.run(
        [str(py), "-m", "pip", "install", "-U", "platformio"],
        capture_output=True, text=True,
    )
    if install.returncode != 0:
        raise RuntimeError(f"Could not install PlatformIO:\n{install.stdout}\n{install.stderr}")

    pio = PENV_DIR / bin_dir / exe
    if not pio.exists():
        raise RuntimeError("PlatformIO installed but `pio` executable not found.")
    return str(pio)


# ---------------------------------------------------------------------------
# Workspace helpers
# ---------------------------------------------------------------------------


def _usable_project_path(path_value: str | None) -> Path | None:
    """Return a real project directory only when it is safe to use locally."""
    if not path_value:
        return None
    try:
        path = Path(path_value).expanduser()
        if not path.exists() or not path.is_dir():
            return None
        if not os.access(path, os.R_OK | os.W_OK):
            return None
        return path
    except OSError:
        return None


def workspace_dir(project_id: str) -> Path:
    """Directory to build/flash in — the same one GitManager syncs DB files into.

    Resolves to the project's real on-disk folder (``project.path``) when it is
    present and usable on this machine. Falls back to the internal
    ``data/workspaces/<id>`` when the path is missing, stale, or inaccessible.
    """
    if str(project_id).isdigit():
        try:
            from db.session import engine
            from sqlmodel import Session, select
            from db.models import ProjectRow
            with Session(engine) as session:
                project = session.exec(
                    select(ProjectRow).where(ProjectRow.id == int(project_id))
                ).first()
                # Use real project folders only when this machine can actually
                # read/write them; imported DBs can contain stale user paths.
                usable_path = _usable_project_path(project.path if project else None)
                if usable_path:
                    return usable_path
        except Exception:
            # Never let DB lookup failure break a build — fall back to internal ws.
            pass
    return WORKSPACES_DIR / str(project_id)


def _project_board_id(project_id: str) -> str | None:
    if not str(project_id).isdigit():
        return None
    try:
        from db.session import engine
        from sqlmodel import Session, select
        from db.models import ProjectRow
        with Session(engine) as session:
            project = session.exec(
                select(ProjectRow).where(ProjectRow.id == int(project_id))
            ).first()
            return project.board_id if project else None
    except Exception:
        return None


def project_board_id(project_id: str) -> str | None:
    """Return the project's persisted board target, when one is available."""
    return _project_board_id(project_id)


def platformio_ini_for_board(board: str = DEFAULT_BOARD) -> str:
    """Render the correct PlatformIO environment for the selected board."""
    device = registry.get(board)
    if device and device.arch == "avr":
        return _PLATFORMIO_INI_TEMPLATE_AVR.format(
            env=board, board=board, upload_speed=device.upload_speed or 115200,
        )
    if device and device.arch == "xtensa" and "arduino" in (device.frameworks or []):
        espressif_platform = "espressif8266" if device.family == "ESP8266" else "espressif32"
        return _PLATFORMIO_INI_TEMPLATE_ESP.format(
            env=board, board=board, espressif_platform=espressif_platform,
            upload_speed=device.upload_speed or 460800,
        )
    if device and device.arch == "xtensa" and "espidf" in (device.frameworks or []):
        return _PLATFORMIO_INI_TEMPLATE_ESPIDF.format(
            env=board, board=board, upload_speed=device.upload_speed or 460800,
        )
    if device and device.arch == "arm-samd":
        return _PLATFORMIO_INI_TEMPLATE_SAMD.format(
            env=board, board=board, upload_speed=device.upload_speed or 921600,
        )
    if device and device.arch == "arduino-generic":
        return _PLATFORMIO_INI_TEMPLATE_ARDUINO_GENERIC.format(
            env=board,
            board=board,
            platform=device.pio_platform or "native",
            upload_speed=device.upload_speed or 115200,
        )
    return _PLATFORMIO_INI_TEMPLATE.format(env=board, board=board)


def platformio_board_id(content: str) -> str | None:
    """Extract the active board id from PlatformIO configuration text."""
    match = re.search(r"(?mi)^\s*board\s*=\s*([^\s;#]+)", content or "")
    return match.group(1).strip() if match else None


def retarget_platformio_content(existing: str, board: str) -> str:
    """Render a board environment while preserving installed dependencies."""
    from services.library_service import _get_lib_deps, _set_lib_deps

    generated = platformio_ini_for_board(board)
    dependencies = _get_lib_deps(existing or "")
    return _set_lib_deps(generated, dependencies) if dependencies else generated


def persist_platformio_content(
    project_id: str,
    content: str,
    *,
    session=None,
    project=None,
) -> Path:
    """Atomically mirror platformio.ini to both DB and the build root.

    Callers inside a transaction may pass their session/project; otherwise this
    helper owns a short DB transaction. A known `board =` value also updates the
    project target so a later build cannot silently retarget the file to STM32.
    """
    from core.config import now_utc
    from db.models import CodeFileRow, ProjectRow
    from db.session import engine
    from sqlmodel import Session, select

    owns_session = session is None
    if owns_session:
        session = Session(engine)
    try:
        if project is None and str(project_id).isdigit():
            project = session.get(ProjectRow, int(project_id))
        if project is None:
            raise ValueError(f"Unknown project_id: {project_id}")

        row = session.exec(
            select(CodeFileRow).where(
                CodeFileRow.project_id == project.id,
                CodeFileRow.path == "platformio.ini",
            )
        ).first()
        if not row:
            row = CodeFileRow(project_id=project.id, path="platformio.ini", language="ini")
        row.content = content
        row.language = "ini"
        row.updated_at = now_utc()
        session.add(row)

        selected_board = platformio_board_id(content)
        if selected_board and registry.get(selected_board):
            project.board_id = selected_board
            project.updated_at = now_utc()
            session.add(project)

        usable = _usable_project_path(project.path)
        workspace = usable or (WORKSPACES_DIR / str(project.id))
        workspace.mkdir(parents=True, exist_ok=True)
        target = workspace / "platformio.ini"
        temporary = workspace / ".platformio.ini.tmp"
        temporary.write_text(content, encoding="utf-8")
        temporary.replace(target)

        if owns_session:
            session.commit()
        return target
    finally:
        if owns_session:
            session.close()


def configure_project_environment(
    project_id: str,
    board: str,
    *,
    session=None,
    project=None,
) -> tuple[object, str, Path]:
    """Select a board and configure its build environment and entry point."""
    device = registry.get(board)
    if not device:
        raise ValueError(f"Unknown board_id: {board}")

    if project is None and session is not None and str(project_id).isdigit():
        from db.models import ProjectRow

        project = session.get(ProjectRow, int(project_id))

    workspace = None
    if project is not None:
        workspace = _usable_project_path(project.path) or (WORKSPACES_DIR / str(project.id))
    else:
        workspace = workspace_dir(project_id)
    ini_path = workspace / "platformio.ini"
    existing = ini_path.read_text(encoding="utf-8") if ini_path.exists() else ""
    content = retarget_platformio_content(existing, device.id)

    # Frameworks do not share an entry-point contract. Safely replace only the
    # untouched generated placeholder (STM32 main.c, Arduino main.cpp, or
    # ESP-IDF main.c); user-authored source is never removed or overwritten.
    if project is not None and session is not None and project.board_id != device.id:
        from core.config import now_utc
        from db.models import CodeFileRow
        from services.projects import default_files
        from sqlmodel import select

        old_entries = {
            file_path: (language, body)
            for file_path, language, body in default_files(project.name, project.board_id)
            if file_path in {"src/main.c", "src/main.cpp"}
        }
        new_entries = [
            item for item in default_files(project.name, device.id)
            if item[0] in {"src/main.c", "src/main.cpp"}
        ]
        for old_path, (_language, old_body) in old_entries.items():
            row = session.exec(
                select(CodeFileRow).where(
                    CodeFileRow.project_id == project.id,
                    CodeFileRow.path == old_path,
                )
            ).first()
            if row and row.content == old_body:
                session.delete(row)
            disk_path = workspace / old_path
            if disk_path.exists():
                try:
                    if disk_path.read_text(encoding="utf-8") == old_body:
                        disk_path.unlink()
                except (OSError, UnicodeError):
                    pass

        for new_path, language, new_body in new_entries:
            row = session.exec(
                select(CodeFileRow).where(
                    CodeFileRow.project_id == project.id,
                    CodeFileRow.path == new_path,
                )
            ).first()
            disk_path = workspace / new_path
            if row is None and not disk_path.exists():
                row = CodeFileRow(
                    project_id=project.id,
                    path=new_path,
                    language=language,
                    content=new_body,
                    updated_at=now_utc(),
                )
                session.add(row)
                disk_path.parent.mkdir(parents=True, exist_ok=True)
                disk_path.write_text(new_body, encoding="utf-8")

    path = persist_platformio_content(
        project_id,
        content,
        session=session,
        project=project,
    )
    return device, content, path


def ensure_platformio_ini(workspace: Path, board: str = DEFAULT_BOARD) -> None:
    """Write a platformio.ini if the project doesn't already ship one."""
    ini = workspace / "platformio.ini"
    if not ini.exists():
        workspace.mkdir(parents=True, exist_ok=True)
        ini.write_text(platformio_ini_for_board(board), encoding="utf-8")


def _find_firmware(workspace: Path) -> str | None:
    build_dir = workspace / ".pio" / "build"
    if not build_dir.exists():
        return None
    for ext in ("*.elf", "*.bin", "*.hex"):
        for fw in build_dir.rglob(ext):
            return str(fw)
    return None


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


# 12-bit DBGMCU DEV_ID -> family, read from the DBGMCU_IDCODE register.
# Values collected from each family's Reference Manual "MCU device ID code"
# section. VERIFY AGAINST THE RM BEFORE FULLY TRUSTING — this table is used
# only to *suggest* a board to the user, never to silently auto-select or
# auto-flash one, so a wrong/missing entry degrades to "select manually"
# rather than doing something destructive.
DBGMCU_IDCODE_MAP: dict[int, str] = {
    0x410: "STM32F1", 0x412: "STM32F1", 0x414: "STM32F1", 0x418: "STM32F1", 0x430: "STM32F1",
    0x411: "STM32F2",
    0x422: "STM32F3", 0x438: "STM32F3", 0x446: "STM32F3", 0x439: "STM32F3", 0x432: "STM32F3",
    0x413: "STM32F4", 0x419: "STM32F4", 0x423: "STM32F4", 0x433: "STM32F4", 0x431: "STM32F4",
    0x421: "STM32F4", 0x434: "STM32F4",
    0x449: "STM32F7", 0x451: "STM32F7",
    0x440: "STM32F0", 0x444: "STM32F0", 0x445: "STM32F0", 0x448: "STM32F0", 0x442: "STM32F0",
    0x460: "STM32G0",
    0x468: "STM32G4", 0x469: "STM32G4",
    0x450: "STM32H7", 0x480: "STM32H7",
    0x484: "STM32H5",
    0x417: "STM32L0",
    0x416: "STM32L1", 0x427: "STM32L1", 0x429: "STM32L1", 0x436: "STM32L1", 0x437: "STM32L1",
    0x415: "STM32L4", 0x461: "STM32L4",
    0x472: "STM32L5",
    0x482: "STM32U5",
    0x495: "STM32WB",
    0x497: "STM32WL",
}

# DBGMCU_IDCODE lives at a different address depending on the core generation.
_IDCODE_ADDR_CANDIDATES = ["0xE0042000", "0x40015800"]


# Try a small set of real, correctly-defined target configs — one per
# Cortex-M core generation OpenOCD ships a distinct DAP setup for — rather
# than hacking a single one's tap-ID check (that approach failed: OpenOCD
# still refused to attach when the actual core didn't match stm32f1x.cfg's
# expected Cortex-M3 DAP). Whichever of these actually matches the
# connected chip will `init` cleanly; the others fail fast and we move on.
_PROBE_TARGET_CFGS = [
    "target/stm32f1x.cfg",
    "target/stm32f4x.cfg",
    "target/stm32f0x.cfg",
    "target/stm32f7x.cfg",
    "target/stm32l5x.cfg",
    "target/stm32u5x.cfg",
]

def probe_connected_chip() -> DeviceStatus:
    """Generic auto-detect: try each core generation's real OpenOCD target
    config until one attaches cleanly, then read the connected chip's
    DBGMCU DEV_ID over SWD and map it to a family.

    This never auto-selects or auto-flashes a board on its own — it only
    populates `detected_family`/`suggested_boards` for the caller/UI to
    offer as a suggestion the user confirms.
    """
    last_detail = ""
    for target_cfg in _PROBE_TARGET_CFGS:
        for addr in _IDCODE_ADDR_CANDIDATES:
            cmd = [
                openocd_bin(),
                "-f", "interface/stlink.cfg",
                "-c", "transport select hla_swd",
                "-f", target_cfg,
                "-c", "init",
                "-c", f"mdw {addr}",
                "-c", "shutdown",
            ]
            try:
                res = subprocess.run(cmd, capture_output=True, text=True, timeout=8)
            except FileNotFoundError:
                return DeviceStatus(connected=False, detail="OpenOCD not found (flash tooling unavailable).")
            except subprocess.TimeoutExpired:
                continue

            blob = f"{res.stdout}\n{res.stderr}"
            m = re.search(rf"{addr}:\s*([0-9a-fA-F]{{8}})", blob)
            if not m:
                if "init mode failed" in blob.lower():
                    last_detail = blob.strip()[-300:]
                continue  # this core generation didn't match — try the next

            dev_id = int(m.group(1), 16) & 0xFFF
            family = DBGMCU_IDCODE_MAP.get(dev_id)
            if family:
                board_candidates = candidates_for_family(
                    family,
                    source="openocd",
                    reason=f"DBGMCU DEV_ID 0x{dev_id:03x} maps to {family}",
                    confidence=0.72,
                )
                suggested = [c.board.id for c in board_candidates]
                return DeviceStatus(
                    connected=True, probe="ST-Link V2",
                    detail=f"Detected DEV_ID 0x{dev_id:03x} — matches {family}.",
                    detected_family=family, suggested_boards=suggested,
                    candidates=[c.as_dict() for c in board_candidates],
                )
            return DeviceStatus(
                connected=True, probe="ST-Link V2",
                detail=f"Chip responded but DEV_ID 0x{dev_id:03x} isn't in our lookup "
                       "table yet — select the board manually.",
            )

    detail = "No ST-Link/board connected, or the chip didn't respond to a generic probe."
    if last_detail:
        detail += f" Last attempt said: {last_detail}"
    return DeviceStatus(connected=False, detail=detail)


def auto_detect_board(project_id: str | None = None, session=None) -> DeviceStatus:
    """Project-aware board detection from project files plus a live chip probe."""
    workspace = workspace_dir(project_id) if project_id else None
    candidates = detect_from_workspace(workspace)
    live = probe_connected_chip()
    candidates = _merge_candidates(
        candidates
        + candidates_for_family(
            live.detected_family,
            source="openocd",
            reason=live.detail,
            confidence=0.72,
        )
    )
    best = candidates[0] if candidates else None

    return DeviceStatus(
        connected=live.connected,
        probe=live.probe,
        target=best.board.label if best else live.target,
        detail=_detection_detail(candidates, live.detail),
        detected_family=best.board.family if best else live.detected_family,
        suggested_boards=[c.board.id for c in candidates],
        candidates=[c.as_dict() for c in candidates],
    )


def _merge_candidates(candidates):
    best = {}
    for candidate in candidates:
        current = best.get(candidate.board.id)
        if current is None or candidate.confidence > current.confidence:
            best[candidate.board.id] = candidate
    return sorted(best.values(), key=lambda c: (-c.confidence, c.board.family, c.board.label))


def _detection_detail(candidates, live_detail: str) -> str:
    if candidates:
        top = candidates[0]
        return f"Best match: {top.board.label} ({top.source}, {top.confidence:.0%})."
    return live_detail or "No board signal found in project files or connected hardware."


def _list_serial_ports() -> list[dict]:
    """Enumerate serial ports via `pio device list --json-output` — reuses
    PlatformIO's own (pyserial-based) port + hwid detection rather than
    adding a direct pyserial dependency, mirroring how the rest of this
    module shells out to `pio` instead of vendoring its internals."""
    pio = pio_bin()
    if not pio:
        return []
    try:
        res = subprocess.run(
            [pio, "device", "list", "--json-output"],
            capture_output=True, text=True, timeout=DETECT_TIMEOUT_S,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    if res.returncode != 0:
        return []
    try:
        import json
        return json.loads(res.stdout)
    except (ValueError, TypeError):
        return []


def detect_device_serial(device) -> DeviceStatus:
    """Shared serial-port detection for boards with no SWD/ST-Link probe
    wired up in this app — AVR (avrdude over a bootloader), ESP32/ESP8266
    (esptool), and SAMD (bossac over the UF2/SAM-BA bootloader) all just
    need a USB serial port to exist; the actual flashing tool does its own
    handshake (STK500/Caterina, esptool's sync sequence, or bossac's
    1200bps touch-reset) once `pio run -t upload` runs. We can't uniquely
    confirm *which* board is attached from the port alone, but the port's
    USB VID:PID (from `pio device list`) often narrows it down — see
    boards/usb_ids.py. Same non-destructive philosophy as
    probe_connected_chip(): suggest, never silently auto-select.
    """
    from boards.usb_ids import parse_hwid, GENUINE_VID_PID, BRIDGE_CHIP_VID_PID
    from boards.detector import BoardCandidate

    ports = _list_serial_ports()
    if not ports:
        return DeviceStatus(
            connected=False, probe="USB Serial",
            detail="No serial port found — plug in the board (driver install "
                   "may be needed for CH340/CP210x/FTDI-based boards).",
        )

    candidates: list[BoardCandidate] = []
    for p in ports:
        ids = parse_hwid(p.get("hwid", ""))
        if not ids:
            continue
        vid, pid = ids
        if (vid, pid) in GENUINE_VID_PID:
            board_id, confidence, reason = GENUINE_VID_PID[(vid, pid)]
            match = registry.get(board_id)
            if match:
                candidates.append(BoardCandidate(board=match, confidence=confidence,
                                                   source="usb_vid_pid", reason=reason))
        elif (vid, pid) in BRIDGE_CHIP_VID_PID:
            for board_id, confidence in BRIDGE_CHIP_VID_PID[(vid, pid)]:
                match = registry.get(board_id)
                if match:
                    candidates.append(BoardCandidate(
                        board=match, confidence=confidence, source="usb_vid_pid",
                        reason=f"VID:PID {vid}:{pid} is a common bridge chip — "
                               "several boards use it, this is a low-confidence guess.",
                    ))

    names = ", ".join(p.get("port", "?") for p in ports)
    if candidates:
        candidates.sort(key=lambda c: -c.confidence)
        top = candidates[0]
        return DeviceStatus(
            connected=True, probe="USB Serial",
            target=device.label,
            detail=f"Serial port(s): {names}. Best VID:PID match: {top.board.label} "
                   f"({top.confidence:.0%}, {top.reason}).",
            detected_family=top.board.family,
            suggested_boards=[c.board.id for c in candidates],
            candidates=[c.as_dict() for c in candidates],
        )

    return DeviceStatus(
        connected=True, probe="USB Serial",
        target=device.label,
        detail=f"Serial port(s) detected: {names}. Couldn't identify the exact board "
               f"from its USB id — upload will auto-select unless multiple boards are attached.",
    )


# Back-compat alias — detect_device_avr was the original name before ESP32/
# ESP8266 started sharing this same serial-detection path.
detect_device_avr = detect_device_serial


def detect_device(board: str | None = None, session=None) -> DeviceStatus:
    if board is None:
        board = DEFAULT_BOARD
    device = registry.get(board) or registry.default()

    if device.arch in ("avr", "xtensa", "arm-samd", "arduino-generic"):
        return detect_device_serial(device)

    cmd = [
        openocd_bin(),
        "-f", device.openocd_interface,
        "-f", device.openocd_target,
        "-c", "init; exit",
    ]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=DETECT_TIMEOUT_S)
    except FileNotFoundError:
        return DeviceStatus(connected=False, detail="OpenOCD not found (flash tooling unavailable).")
    except subprocess.TimeoutExpired:
        return DeviceStatus(connected=False, detail="Device probe timed out.")

    # OpenOCD prints diagnostics on stderr. Heuristics: success markers vs the
    # well-known "no device" / "unable to open" failures.
    blob = f"{res.stdout}\n{res.stderr}".lower()
    if res.returncode == 0 and ("stlink" in blob or "target voltage" in blob) and "error" not in blob:
        return DeviceStatus(
            connected=True,
            probe="ST-Link V2",
            target=device.label,
            detail="ST-Link detected over SWD.",
        )
    if "no device found" in blob or "unable to open" in blob or "libusb_open" in blob:
        return DeviceStatus(connected=False, probe="ST-Link V2", detail="No ST-Link/board connected.")
    # Adapter present but target not reachable (e.g. board unpowered).
    if "stlink" in blob and "init mode failed" in blob:
        return DeviceStatus(
            connected=False, probe="ST-Link V2",
            detail="ST-Link present but no target detected (check wiring/power).",
        )
    return DeviceStatus(connected=False, detail=(res.stderr or res.stdout or "No device detected.").strip()[:500])


# ---------------------------------------------------------------------------
# Build / flash
# ---------------------------------------------------------------------------


def build_project(project_id: str, board: str | None = None, session=None) -> BuildResult:
    if board is None:
        if session is not None:
            from boards import device_manager
            board = device_manager.for_project(project_id, session).id
        else:
            board = _project_board_id(project_id) or DEFAULT_BOARD
    """Run a real PlatformIO build in the project workspace. Always returns output."""
    workspace = workspace_dir(project_id)
    if not workspace.exists():
        return BuildResult(success=False, returncode=1,
                            output="Workspace not found — sync project files first.")

    try:
        pio = ensure_platformio()
    except RuntimeError as exc:
        return BuildResult(success=False, returncode=127,
                           output=f"Toolchain unavailable: {exc}")

    ensure_platformio_ini(workspace, board)

    started = time.monotonic()
    try:
        res = subprocess.run(
            [pio, "run", "-d", str(workspace)],
            capture_output=True, text=True, timeout=BUILD_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return BuildResult(success=False, returncode=124,
                           output="Build timed out.", duration_s=time.monotonic() - started)

    output = (res.stdout or "") + (res.stderr or "")
    return BuildResult(
        success=res.returncode == 0,
        returncode=res.returncode,
        output=output,
        firmware_path=_find_firmware(workspace) if res.returncode == 0 else None,
        duration_s=round(time.monotonic() - started, 2),
    )


def build_project_stream(project_id: str, board: str | None = None):
    if board is None:
        board = _project_board_id(project_id) or DEFAULT_BOARD
    """Run a real PlatformIO build, yielding output line-by-line as it runs.

    Yields dicts:
      {"type": "line", "text": str}                      one stdout/stderr line
      {"type": "status", "text": str}                    lifecycle notes (e.g. provisioning)
      {"type": "done", "success": bool, "returncode": int,
       "firmware_path": str|None, "duration_s": float,
       "output": str}                                    terminal event w/ full log

    Generator (blocking I/O); a caller should iterate it on a worker thread and
    forward events to the client. Never raises — failures surface as a done event.
    """
    workspace = workspace_dir(project_id)
    if not workspace.exists():
        yield {"type": "done", "success": False, "returncode": 1,
               "firmware_path": None, "duration_s": 0.0,
               "output": "Workspace not found — sync project files first."}
        return

    try:
        yield {"type": "status", "text": "Resolving build toolchain (PlatformIO)…"}
        pio = ensure_platformio()
    except RuntimeError as exc:
        yield {"type": "done", "success": False, "returncode": 127,
               "firmware_path": None, "duration_s": 0.0,
               "output": f"Toolchain unavailable: {exc}"}
        return

    ensure_platformio_ini(workspace, board)
    yield {"type": "status", "text": "Compiling firmware…"}

    started = time.monotonic()
    lines: list[str] = []
    try:
        proc = subprocess.Popen(
            [pio, "run", "-d", str(workspace)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,  # merge so the log reads in real order
            text=True,
            bufsize=1,  # line-buffered
        )
    except FileNotFoundError as exc:
        yield {"type": "done", "success": False, "returncode": 127,
               "firmware_path": None, "duration_s": 0.0,
               "output": f"Could not start PlatformIO: {exc}"}
        return

    try:
        assert proc.stdout is not None
        for raw in proc.stdout:
            line = raw.rstrip("\n")
            lines.append(line)
            yield {"type": "line", "text": line}
            if time.monotonic() - started > BUILD_TIMEOUT_S:
                proc.kill()
                lines.append("Build timed out.")
                yield {"type": "line", "text": "Build timed out."}
                break
        returncode = proc.wait(timeout=10)
    except Exception as exc:  # noqa: BLE001 — surface, don't crash the stream
        proc.kill()
        returncode = proc.returncode if proc.returncode is not None else 1
        lines.append(f"Build error: {exc}")
        yield {"type": "line", "text": f"Build error: {exc}"}

    success = returncode == 0
    yield {
        "type": "done",
        "success": success,
        "returncode": returncode,
        "firmware_path": _find_firmware(workspace) if success else None,
        "duration_s": round(time.monotonic() - started, 2),
        "output": "\n".join(lines),
    }


def flash_project(project_id: str, board: str | None = None, session=None) -> FlashResult:
    if board is None:
        if session is not None:
            from boards import device_manager
            board = device_manager.for_project(project_id, session).id
        else:
            board = _project_board_id(project_id) or DEFAULT_BOARD
    """Build (if needed) then flash via `pio run -t upload`, gated on detection."""
    device = detect_device(board)
    if not device.connected:
        return FlashResult(flashed=False, reason="no_device",
                           output=device.detail, device=device)

    workspace = workspace_dir(project_id)
    try:
        pio = ensure_platformio()
    except RuntimeError as exc:
        return FlashResult(flashed=False, reason="flash_failed",
                           returncode=127, output=f"Toolchain unavailable: {exc}", device=device)

    ensure_platformio_ini(workspace, board)
    try:
        res = subprocess.run(
            [pio, "run", "-d", str(workspace), "-t", "upload"],
            capture_output=True, text=True, timeout=FLASH_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return FlashResult(flashed=False, reason="flash_failed",
                           returncode=124, output="Flash timed out.", device=device)

    output = (res.stdout or "") + (res.stderr or "")
    ok = res.returncode == 0
    return FlashResult(
        flashed=ok,
        reason="" if ok else "flash_failed",
        returncode=res.returncode,
        output=output,
        device=device,
    )
