"""Real STM32 build / flash / device-detection.

Shells out to PlatformIO (build + flash) and OpenOCD (ST-Link detection over SWD)
against the on-disk project workspace that GitManager already materializes at
``backend/data/workspaces/<project_id>/``. Mirrors the ``subprocess.run`` pattern
in :mod:`agent.git_manager`.

Toolchain resolution favors an app-owned PlatformIO/OpenOCD so the shipped app
needs no manual installs:
  - PlatformIO: ``$PIO_BIN`` -> app venv ``data/penv/bin/pio`` -> ``~/.platformio``.
    If none exist, :func:`ensure_platformio` auto-provisions one into ``data/penv``.
  - OpenOCD: ``$OPENOCD_BIN`` -> vendored ``vendor/openocd/<platform>/bin/openocd``
    -> ``openocd`` on PATH.

Default target is the STM32F103C8 Blue Pill flashed via ST-Link.
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path
import re

from schemas import BuildResult, DeviceStatus, FlashResult
from boards.registry import registry

BACKEND_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BACKEND_DIR / "data"
WORKSPACES_DIR = DATA_DIR / "workspaces"
PENV_DIR = DATA_DIR / "penv"
VENDOR_DIR = BACKEND_DIR / "vendor"


DEFAULT_BOARD = registry.default().id
DEFAULT_BOARD_LABEL = registry.default().label

# Bound the time any single shelled command may run so a stuck probe/build can't
# hang a request forever.
DETECT_TIMEOUT_S = 15
BUILD_TIMEOUT_S = 600
FLASH_TIMEOUT_S = 180

_PLATFORMIO_INI_TEMPLATE = """; Auto-generated by HardcoreAI — edit to retarget.
[env:{env}]
platform = ststm32
board = {board}
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
""".format(env=DEFAULT_BOARD, board=DEFAULT_BOARD)


# ---------------------------------------------------------------------------
# Toolchain resolution
# ---------------------------------------------------------------------------


def _platform_slug() -> str:
    if sys.platform.startswith("win"):
        return "windows"
    if sys.platform == "darwin":
        return "macos"
    return "linux"


def _pio_candidates() -> list[Path]:
    exe = "pio.exe" if sys.platform.startswith("win") else "pio"
    bin_dir = "Scripts" if sys.platform.startswith("win") else "bin"
    return [
        PENV_DIR / bin_dir / exe,
        Path.home() / ".platformio" / "penv" / bin_dir / exe,
    ]


def pio_bin() -> str | None:
    """Resolve an existing PlatformIO executable, or None if not installed yet."""
    override = os.environ.get("PIO_BIN")
    if override and Path(override).exists():
        return override
    for cand in _pio_candidates():
        if cand.exists():
            return str(cand)
    return None


def openocd_bin() -> str:
    """Resolve OpenOCD: env override -> vendored -> PATH (`openocd`)."""
    override = os.environ.get("OPENOCD_BIN")
    if override:
        return override
    exe = "openocd.exe" if sys.platform.startswith("win") else "openocd"
    vendored = VENDOR_DIR / "openocd" / _platform_slug() / "bin" / exe
    if vendored.exists():
        return str(vendored)
    return "openocd"


def ensure_platformio() -> str:
    """Return a usable `pio` path, provisioning an app-owned core if needed.

    Creates ``data/penv`` and ``pip install platformio`` into it on first use so
    the end user never installs anything manually. Raises RuntimeError on failure.
    """
    found = pio_bin()
    if found:
        return found

    bin_dir = "Scripts" if sys.platform.startswith("win") else "bin"
    exe = "pio.exe" if sys.platform.startswith("win") else "pio"
    PENV_DIR.parent.mkdir(parents=True, exist_ok=True)

    # Build an isolated venv and install PlatformIO into it.
    venv = subprocess.run(
        [sys.executable, "-m", "venv", str(PENV_DIR)],
        capture_output=True, text=True,
    )
    if venv.returncode != 0:
        raise RuntimeError(f"Could not create PlatformIO venv:\n{venv.stderr}")

    py = PENV_DIR / bin_dir / ("python.exe" if sys.platform.startswith("win") else "python")
    install = subprocess.run(
        [str(py), "-m", "pip", "install", "-U", "platformio"],
        capture_output=True, text=True,
    )
    if install.returncode != 0:
        raise RuntimeError(f"Could not install PlatformIO:\n{install.stdout}\n{install.stderr}")

    pio = PENV_DIR / bin_dir / exe
    if not pio.exists():
        raise RuntimeError("PlatformIO installed but `pio` executable not found.")
    return str(pio)


# ---------------------------------------------------------------------------
# Workspace helpers
# ---------------------------------------------------------------------------


def workspace_dir(project_id: str) -> Path:
    """Directory to build/flash in — the same one GitManager syncs DB files into.

    Resolves to the project's real on-disk folder (``project.path``) when one is
    set, so build artifacts (platformio.ini, .pio/) land next to the user's code
    where they expect them. Falls back to the internal ``data/workspaces/<id>``
    only for projects with no real path (mirrors GitManager's resolution).
    """
    if str(project_id).isdigit():
        try:
            from db.session import engine
            from sqlmodel import Session, select
            from db.models import ProjectRow
            with Session(engine) as session:
                project = session.exec(
                    select(ProjectRow).where(ProjectRow.id == int(project_id))
                ).first()
                # Match GitManager's resolution exactly: use the real folder only
                # when it is an initialized repo, otherwise the internal workspace.
                # This guarantees the build dir is the same one sync writes into.
                if project and project.path:
                    return Path(project.path)
        except Exception:
            # Never let DB lookup failure break a build — fall back to internal ws.
            pass
    return WORKSPACES_DIR / str(project_id)


def ensure_platformio_ini(workspace: Path, board: str = DEFAULT_BOARD) -> None:
    """Write a platformio.ini if the project doesn't already ship one."""
    ini = workspace / "platformio.ini"
    if not ini.exists():
        workspace.mkdir(parents=True, exist_ok=True)
        ini.write_text(_PLATFORMIO_INI_TEMPLATE.format(env=board, board=board), encoding="utf-8")


def _find_firmware(workspace: Path) -> str | None:
    build_dir = workspace / ".pio" / "build"
    if not build_dir.exists():
        return None
    for ext in ("*.elf", "*.bin", "*.hex"):
        for fw in build_dir.rglob(ext):
            return str(fw)
    return None


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


# 12-bit DBGMCU DEV_ID -> family, read from the DBGMCU_IDCODE register.
# Values collected from each family's Reference Manual "MCU device ID code"
# section. VERIFY AGAINST THE RM BEFORE FULLY TRUSTING — this table is used
# only to *suggest* a board to the user, never to silently auto-select or
# auto-flash one, so a wrong/missing entry degrades to "select manually"
# rather than doing something destructive.
DBGMCU_IDCODE_MAP: dict[int, str] = {
    0x410: "STM32F1", 0x412: "STM32F1", 0x414: "STM32F1", 0x418: "STM32F1", 0x430: "STM32F1",
    0x411: "STM32F2",
    0x422: "STM32F3", 0x438: "STM32F3", 0x446: "STM32F3", 0x439: "STM32F3", 0x432: "STM32F3",
    0x413: "STM32F4", 0x419: "STM32F4", 0x423: "STM32F4", 0x433: "STM32F4", 0x431: "STM32F4",
    0x421: "STM32F4", 0x434: "STM32F4",
    0x449: "STM32F7", 0x451: "STM32F7",
    0x440: "STM32F0", 0x444: "STM32F0", 0x445: "STM32F0", 0x448: "STM32F0", 0x442: "STM32F0",
    0x460: "STM32G0",
    0x468: "STM32G4", 0x469: "STM32G4",
    0x450: "STM32H7", 0x480: "STM32H7",
    0x484: "STM32H5",
    0x417: "STM32L0",
    0x416: "STM32L1", 0x427: "STM32L1", 0x429: "STM32L1", 0x436: "STM32L1", 0x437: "STM32L1",
    0x415: "STM32L4", 0x461: "STM32L4",
    0x472: "STM32L5",
    0x482: "STM32U5",
    0x495: "STM32WB",
    0x497: "STM32WL",
}

# DBGMCU_IDCODE lives at a different address depending on the core generation.
_IDCODE_ADDR_CANDIDATES = ["0xE0042000", "0x40015800"]


# Try a small set of real, correctly-defined target configs — one per
# Cortex-M core generation OpenOCD ships a distinct DAP setup for — rather
# than hacking a single one's tap-ID check (that approach failed: OpenOCD
# still refused to attach when the actual core didn't match stm32f1x.cfg's
# expected Cortex-M3 DAP). Whichever of these actually matches the
# connected chip will `init` cleanly; the others fail fast and we move on.
_PROBE_TARGET_CFGS = [
    "target/stm32f1x.cfg",
    "target/stm32f4x.cfg",
    "target/stm32f0x.cfg",
    "target/stm32f7x.cfg",
    "target/stm32l5x.cfg",
    "target/stm32u5x.cfg",
]

def probe_connected_chip() -> DeviceStatus:
    """Generic auto-detect: try each core generation's real OpenOCD target
    config until one attaches cleanly, then read the connected chip's
    DBGMCU DEV_ID over SWD and map it to a family.

    This never auto-selects or auto-flashes a board on its own — it only
    populates `detected_family`/`suggested_boards` for the caller/UI to
    offer as a suggestion the user confirms.
    """
    last_detail = ""
    for target_cfg in _PROBE_TARGET_CFGS:
        for addr in _IDCODE_ADDR_CANDIDATES:
            cmd = [
                openocd_bin(),
                "-f", "interface/stlink.cfg",
                "-c", "transport select hla_swd",
                "-f", target_cfg,
                "-c", "init",
                "-c", f"mdw {addr}",
                "-c", "shutdown",
            ]
            try:
                res = subprocess.run(cmd, capture_output=True, text=True, timeout=8)
            except FileNotFoundError:
                return DeviceStatus(connected=False, detail="OpenOCD not found (flash tooling unavailable).")
            except subprocess.TimeoutExpired:
                continue

            blob = f"{res.stdout}\n{res.stderr}"
            m = re.search(rf"{addr}:\s*([0-9a-fA-F]{{8}})", blob)
            if not m:
                if "init mode failed" in blob.lower():
                    last_detail = blob.strip()[-300:]
                continue  # this core generation didn't match — try the next

            dev_id = int(m.group(1), 16) & 0xFFF
            family = DBGMCU_IDCODE_MAP.get(dev_id)
            if family:
                suggested = [b.id for b in registry.list() if b.family == family]
                return DeviceStatus(
                    connected=True, probe="ST-Link V2",
                    detail=f"Detected DEV_ID 0x{dev_id:03x} — matches {family}.",
                    detected_family=family, suggested_boards=suggested,
                )
            return DeviceStatus(
                connected=True, probe="ST-Link V2",
                detail=f"Chip responded but DEV_ID 0x{dev_id:03x} isn't in our lookup "
                       "table yet — select the board manually.",
            )

    detail = "No ST-Link/board connected, or the chip didn't respond to a generic probe."
    if last_detail:
        detail += f" Last attempt said: {last_detail}"
    return DeviceStatus(connected=False, detail=detail)


def detect_device(board: str | None = None, session=None) -> DeviceStatus:
    if board is None:
        board = DEFAULT_BOARD
    device = registry.get(board) or registry.default()
    cmd = [
        openocd_bin(),
        "-f", device.openocd_interface,
        "-f", device.openocd_target,
        "-c", "init; exit",
    ]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=DETECT_TIMEOUT_S)
    except FileNotFoundError:
        return DeviceStatus(connected=False, detail="OpenOCD not found (flash tooling unavailable).")
    except subprocess.TimeoutExpired:
        return DeviceStatus(connected=False, detail="Device probe timed out.")

    # OpenOCD prints diagnostics on stderr. Heuristics: success markers vs the
    # well-known "no device" / "unable to open" failures.
    blob = f"{res.stdout}\n{res.stderr}".lower()
    if res.returncode == 0 and ("stlink" in blob or "target voltage" in blob) and "error" not in blob:
        return DeviceStatus(
            connected=True,
            probe="ST-Link V2",
            target=device.label,
            detail="ST-Link detected over SWD.",
        )
    if "no device found" in blob or "unable to open" in blob or "libusb_open" in blob:
        return DeviceStatus(connected=False, probe="ST-Link V2", detail="No ST-Link/board connected.")
    # Adapter present but target not reachable (e.g. board unpowered).
    if "stlink" in blob and "init mode failed" in blob:
        return DeviceStatus(
            connected=False, probe="ST-Link V2",
            detail="ST-Link present but no target detected (check wiring/power).",
        )
    return DeviceStatus(connected=False, detail=(res.stderr or res.stdout or "No device detected.").strip()[:500])


# ---------------------------------------------------------------------------
# Build / flash
# ---------------------------------------------------------------------------


def build_project(project_id: str, board: str | None = None, session=None) -> BuildResult:
    if board is None:
        if session is not None:
            from boards import device_manager
            board = device_manager.for_project(project_id, session).id
        else:
            board = DEFAULT_BOARD
    """Run a real PlatformIO build in the project workspace. Always returns output."""
    workspace = workspace_dir(project_id)
    if not workspace.exists():
        return BuildResult(success=False, returncode=1,
                            output="Workspace not found — sync project files first.")

    try:
        pio = ensure_platformio()
    except RuntimeError as exc:
        return BuildResult(success=False, returncode=127,
                           output=f"Toolchain unavailable: {exc}")

    ensure_platformio_ini(workspace, board)

    started = time.monotonic()
    try:
        res = subprocess.run(
            [pio, "run", "-d", str(workspace)],
            capture_output=True, text=True, timeout=BUILD_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return BuildResult(success=False, returncode=124,
                           output="Build timed out.", duration_s=time.monotonic() - started)

    output = (res.stdout or "") + (res.stderr or "")
    return BuildResult(
        success=res.returncode == 0,
        returncode=res.returncode,
        output=output,
        firmware_path=_find_firmware(workspace) if res.returncode == 0 else None,
        duration_s=round(time.monotonic() - started, 2),
    )


def build_project_stream(project_id: str, board: str = DEFAULT_BOARD):
    """Run a real PlatformIO build, yielding output line-by-line as it runs.

    Yields dicts:
      {"type": "line", "text": str}                      one stdout/stderr line
      {"type": "status", "text": str}                    lifecycle notes (e.g. provisioning)
      {"type": "done", "success": bool, "returncode": int,
       "firmware_path": str|None, "duration_s": float,
       "output": str}                                    terminal event w/ full log

    Generator (blocking I/O); a caller should iterate it on a worker thread and
    forward events to the client. Never raises — failures surface as a done event.
    """
    workspace = workspace_dir(project_id)
    if not workspace.exists():
        yield {"type": "done", "success": False, "returncode": 1,
               "firmware_path": None, "duration_s": 0.0,
               "output": "Workspace not found — sync project files first."}
        return

    try:
        yield {"type": "status", "text": "Resolving build toolchain (PlatformIO)…"}
        pio = ensure_platformio()
    except RuntimeError as exc:
        yield {"type": "done", "success": False, "returncode": 127,
               "firmware_path": None, "duration_s": 0.0,
               "output": f"Toolchain unavailable: {exc}"}
        return

    ensure_platformio_ini(workspace, board)
    yield {"type": "status", "text": "Compiling firmware…"}

    started = time.monotonic()
    lines: list[str] = []
    try:
        proc = subprocess.Popen(
            [pio, "run", "-d", str(workspace)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,  # merge so the log reads in real order
            text=True,
            bufsize=1,  # line-buffered
        )
    except FileNotFoundError as exc:
        yield {"type": "done", "success": False, "returncode": 127,
               "firmware_path": None, "duration_s": 0.0,
               "output": f"Could not start PlatformIO: {exc}"}
        return

    try:
        assert proc.stdout is not None
        for raw in proc.stdout:
            line = raw.rstrip("\n")
            lines.append(line)
            yield {"type": "line", "text": line}
            if time.monotonic() - started > BUILD_TIMEOUT_S:
                proc.kill()
                lines.append("Build timed out.")
                yield {"type": "line", "text": "Build timed out."}
                break
        returncode = proc.wait(timeout=10)
    except Exception as exc:  # noqa: BLE001 — surface, don't crash the stream
        proc.kill()
        returncode = proc.returncode if proc.returncode is not None else 1
        lines.append(f"Build error: {exc}")
        yield {"type": "line", "text": f"Build error: {exc}"}

    success = returncode == 0
    yield {
        "type": "done",
        "success": success,
        "returncode": returncode,
        "firmware_path": _find_firmware(workspace) if success else None,
        "duration_s": round(time.monotonic() - started, 2),
        "output": "\n".join(lines),
    }


def flash_project(project_id: str, board: str | None = None, session=None) -> FlashResult:
    if board is None:
        if session is not None:
            from boards import device_manager
            board = device_manager.for_project(project_id, session).id
        else:
            board = DEFAULT_BOARD
    """Build (if needed) then flash via `pio run -t upload`, gated on detection."""
    device = detect_device(board)
    if not device.connected:
        return FlashResult(flashed=False, reason="no_device",
                           output=device.detail, device=device)

    workspace = workspace_dir(project_id)
    try:
        pio = ensure_platformio()
    except RuntimeError as exc:
        return FlashResult(flashed=False, reason="flash_failed",
                           returncode=127, output=f"Toolchain unavailable: {exc}", device=device)

    ensure_platformio_ini(workspace, board)
    try:
        res = subprocess.run(
            [pio, "run", "-d", str(workspace), "-t", "upload"],
            capture_output=True, text=True, timeout=FLASH_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        return FlashResult(flashed=False, reason="flash_failed",
                           returncode=124, output="Flash timed out.", device=device)

    output = (res.stdout or "") + (res.stderr or "")
    ok = res.returncode == 0
    return FlashResult(
        flashed=ok,
        reason="" if ok else "flash_failed",
        returncode=res.returncode,
        output=output,
        device=device,
    )
