"""ESP-IDF code generation for ESP boards that do not use Arduino."""

from __future__ import annotations

import textwrap
from typing import Any

from boards.registry import registry


def generate_espidf_files(board: str, peripherals: list[dict[str, Any]]) -> dict[str, str]:
    device = registry.get(board)
    label = device.label if device else board
    ids = {p.get("id", "").lower() for p in peripherals}

    includes = [
        '#include "freertos/FreeRTOS.h"',
        '#include "freertos/task.h"',
        '#include "esp_log.h"',
    ]
    setup_lines = ['ESP_LOGI(TAG, "Booting HardcoreAI ESP-IDF app for %s", TARGET_BOARD);']
    loop_lines = ['ESP_LOGI(TAG, "tick");', 'vTaskDelay(pdMS_TO_TICKS(1000));']
    notes: list[str] = []

    if "gpio" in ids:
        includes.append('#include "driver/gpio.h"')
        setup_lines.extend([
            "gpio_reset_pin(LED_GPIO);",
            "gpio_set_direction(LED_GPIO, GPIO_MODE_OUTPUT);",
        ])
        loop_lines = [
            "gpio_set_level(LED_GPIO, 1);",
            "vTaskDelay(pdMS_TO_TICKS(500));",
            "gpio_set_level(LED_GPIO, 0);",
            "vTaskDelay(pdMS_TO_TICKS(500));",
        ]
    if "adc1" in ids:
        includes.append('#include "driver/adc.h"')
        notes.append("ADC setup is chip-specific in ESP-IDF; choose an ADC channel valid for this board variant.")
    if "i2c1" in ids:
        includes.append('#include "driver/i2c.h"')
        notes.append("I2C pins are board-variant specific; set SDA/SCL GPIOs before using this scaffold.")
    if "spi1" in ids:
        includes.append('#include "driver/spi_master.h"')
        notes.append("SPI pins are board-variant specific; set MOSI/MISO/SCLK/CS GPIOs before using this scaffold.")
    if "wifi" in ids:
        includes.extend([
            '#include "esp_wifi.h"',
            '#include "esp_event.h"',
            '#include "nvs_flash.h"',
        ])
        setup_lines.extend([
            "ESP_ERROR_CHECK(nvs_flash_init());",
            "ESP_ERROR_CHECK(esp_netif_init());",
            "ESP_ERROR_CHECK(esp_event_loop_create_default());",
            "// Configure esp_wifi_init()/esp_wifi_set_config() with your SSID/password here.",
        ])
    skipped = sorted(ids & {"rcc", "dma", "nvic", "tim1", "usart1", "usart2"})
    if skipped:
        notes.append(
            f"Skipped {', '.join(skipped)}: ESP-IDF uses FreeRTOS/drivers, not STM32 RCC/DMA/NVIC/HAL templates."
        )

    includes = list(dict.fromkeys(includes))
    note_block = "\n".join(f"// Note: {note}" for note in notes)
    if note_block:
        note_block += "\n\n"

    content = f"""// main.c - generated by HardcoreAI for {label}
{note_block}{chr(10).join(includes)}

static const char *TAG = "hardcoreai";
static const char *TARGET_BOARD = "{board}";
static const gpio_num_t LED_GPIO = GPIO_NUM_2;  // change for your board

void app_main(void)
{{
{textwrap.indent(chr(10).join(setup_lines), "    ")}

    while (true) {{
{textwrap.indent(chr(10).join(loop_lines), "        ")}
    }}
}}
"""
    return {"src/main.c": content}
