"""Self-healing schema migrations, run once at application startup.

Verifies connectivity early (a bad password fails loudly here), migrates the
legacy ``projects.user_id`` column to ``uuid``, enables row-level security on
the user-owned tables, and creates the access policies if absent.
"""

from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from sqlalchemy import text
from sqlmodel import Session

from db.session import engine


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Verify connectivity early so a bad password fails loudly at startup.
    with Session(engine) as session:
        session.exec(text("SELECT 1"))

        # Self-healing migrations for user auth and isolation
        session.exec(text("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'projects'
                      AND column_name = 'user_id'
                      AND data_type = 'bigint'
                ) THEN
                    ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS fk_projects_user_id;
                    ALTER TABLE public.projects ALTER COLUMN user_id TYPE uuid USING (NULL);
                END IF;
            END $$;
        """))

        session.exec(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.table_constraints
                    WHERE constraint_name = 'fk_projects_user_id'
                ) THEN
                    ALTER TABLE public.projects
                      ADD CONSTRAINT fk_projects_user_id
                      FOREIGN KEY (user_id)
                      REFERENCES auth.users (id)
                      ON DELETE CASCADE;
                END IF;
            END $$;
        """))

        # Enable RLS
        session.exec(text("""
            ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.project_components ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.project_connections ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.code_files ENABLE ROW LEVEL SECURITY;
        """))

        session.exec(text("""
            ALTER TABLE public.project_connections
              ADD COLUMN IF NOT EXISTS label text,
              ADD COLUMN IF NOT EXISTS color text;
        """))

        # Agent chat history — one JSON blob per project. New table (not seeded by
        # the Supabase migration), so create it here if missing.
        session.exec(text("""
            CREATE TABLE IF NOT EXISTS public.conversations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id bigint NOT NULL UNIQUE REFERENCES public.projects (id) ON DELETE CASCADE,
                history jsonb NOT NULL DEFAULT '[]'::jsonb,
                updated_at timestamptz NOT NULL DEFAULT now()
            );
        """))
        session.exec(text("ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;"))

        # Policies
        session.exec(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can read components') THEN
                    CREATE POLICY "Anyone can read components"
                      ON public.components FOR SELECT TO authenticated USING (true);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can read pins') THEN
                    CREATE POLICY "Anyone can read pins"
                      ON public.pins FOR SELECT TO authenticated USING (true);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own projects') THEN
                    CREATE POLICY "Users can manage their own projects"
                      ON public.projects FOR ALL TO authenticated
                      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage components of their own projects') THEN
                    CREATE POLICY "Users can manage components of their own projects"
                      ON public.project_components FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_components.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_components.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage connections of their own projects') THEN
                    CREATE POLICY "Users can manage connections of their own projects"
                      ON public.project_connections FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_connections.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_connections.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage code files of their own projects') THEN
                    CREATE POLICY "Users can manage code files of their own projects"
                      ON public.code_files FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = code_files.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = code_files.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage conversations of their own projects') THEN
                    CREATE POLICY "Users can manage conversations of their own projects"
                      ON public.conversations FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = conversations.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = conversations.project_id AND projects.user_id = auth.uid()));
                END IF;
            END $$;
        """))
        session.commit()
    yield
