"""Self-healing schema migrations, run once at application startup.

Verifies connectivity early (a bad password fails loudly here), migrates the
legacy ``projects.user_id`` column to ``uuid``, enables row-level security on
the user-owned tables, and creates the access policies if absent.
"""

from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from sqlalchemy import text
from sqlmodel import Session

from db.session import engine


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Verify connectivity early so a bad password fails loudly at startup.
    with Session(engine) as session:
        session.exec(text("SELECT 1"))

        # Self-healing migrations for user auth and isolation
        session.exec(text("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'projects'
                      AND column_name = 'user_id'
                      AND data_type = 'bigint'
                ) THEN
                    ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS fk_projects_user_id;
                    ALTER TABLE public.projects ALTER COLUMN user_id TYPE uuid USING (NULL);
                END IF;
            END $$;
        """))

        session.exec(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.table_constraints
                    WHERE constraint_name = 'fk_projects_user_id'
                ) THEN
                    ALTER TABLE public.projects
                      ADD CONSTRAINT fk_projects_user_id
                      FOREIGN KEY (user_id)
                      REFERENCES auth.users (id)
                      ON DELETE CASCADE;
                END IF;
            END $$;
        """))

        # Enable RLS
        session.exec(text("""
            ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.project_components ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.project_connections ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public.code_files ENABLE ROW LEVEL SECURITY;
        """))

        session.exec(text("""
            ALTER TABLE public.project_connections
              ADD COLUMN IF NOT EXISTS label text,
              ADD COLUMN IF NOT EXISTS color text;
        """))

        # Component catalogue metadata used by the research/component-selection
        # flow. Existing deployments keep working because all columns are
        # nullable or default to empty JSON arrays.
        session.exec(text("""
            ALTER TABLE public.components
              ADD COLUMN IF NOT EXISTS library_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
              ADD COLUMN IF NOT EXISTS buy_links jsonb NOT NULL DEFAULT '[]'::jsonb,
              ADD COLUMN IF NOT EXISTS datasheet_url text,
              ADD COLUMN IF NOT EXISTS aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
              ADD COLUMN IF NOT EXISTS source_url text,
              ADD COLUMN IF NOT EXISTS source_name text,
              ADD COLUMN IF NOT EXISTS image_source_url text,
              ADD COLUMN IF NOT EXISTS discovery_query text,
              ADD COLUMN IF NOT EXISTS discovered_at timestamptz,
              ADD COLUMN IF NOT EXISTS verified_at timestamptz;
        """))
        session.exec(text("""
            ALTER TABLE public.components
              ADD COLUMN IF NOT EXISTS protocols jsonb NOT NULL DEFAULT '[]'::jsonb,
              ADD COLUMN IF NOT EXISTS verification_sources jsonb NOT NULL DEFAULT '[]'::jsonb;
        """))

        # Agent chat history — one JSON blob per project. New table (not seeded by
        # the Supabase migration), so create it here if missing.
        session.exec(text("""
            CREATE TABLE IF NOT EXISTS public.conversations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id bigint NOT NULL UNIQUE REFERENCES public.projects (id) ON DELETE CASCADE,
                history jsonb NOT NULL DEFAULT '[]'::jsonb,
                updated_at timestamptz NOT NULL DEFAULT now()
            );
        """))
        session.exec(text("ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;"))

        session.exec(text("""
            CREATE TABLE IF NOT EXISTS public.ai_usage (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
                project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL,
                provider text NOT NULL DEFAULT '', model text NOT NULL DEFAULT '', request_type text NOT NULL DEFAULT '',
                input_tokens integer NOT NULL DEFAULT 0, output_tokens integer NOT NULL DEFAULT 0,
                total_tokens integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ai_usage_user_created_idx ON public.ai_usage(user_id, created_at DESC);
            CREATE INDEX IF NOT EXISTS ai_usage_created_idx ON public.ai_usage(created_at DESC);
            ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;
        """))

        # OAuth identity stays in auth.users; product onboarding belongs in a
        # small application profile table so existing accounts remain valid.
        session.exec(text("""
            CREATE TABLE IF NOT EXISTS public.user_profiles (
              user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
              company_name text, phone_number text, role text, about text, primary_use_case text,
              company_size text, referral_source text,
              project_limit_unlocked boolean NOT NULL DEFAULT false,
              willing_to_pay boolean,
              project_limit_feedback text,
              completed_at timestamptz,
              updated_at timestamptz NOT NULL DEFAULT now(),
              CONSTRAINT user_profiles_company_name_length CHECK (company_name IS NULL OR char_length(company_name) <= 160),
              CONSTRAINT user_profiles_about_length CHECK (about IS NULL OR char_length(about) <= 600),
              CONSTRAINT user_profiles_role_valid CHECK (role IS NULL OR role IN ('Student', 'Hobbyist / Maker', 'Embedded Engineer', 'Firmware Engineer', 'Hardware Engineer', 'Researcher', 'Startup Founder', 'Product / Engineering', 'Other')),
              CONSTRAINT user_profiles_primary_use_case_valid CHECK (primary_use_case IS NULL OR primary_use_case IN ('Firmware Development', 'Hardware Prototyping', 'PCB / Electronics Development', 'Debugging', 'Research', 'Learning', 'Product Development', 'Other')),
              CONSTRAINT user_profiles_company_size_valid CHECK (company_size IS NULL OR company_size IN ('Individual', '2-10', '11-50', '51-200', '200+')),
              CONSTRAINT user_profiles_referral_source_valid CHECK (referral_source IS NULL OR referral_source IN ('LinkedIn', 'Friend / Colleague', 'University', 'GitHub', 'Search', 'Event', 'Other'))
            );
            ALTER TABLE public.user_profiles
              ADD COLUMN IF NOT EXISTS phone_number text,
              ADD COLUMN IF NOT EXISTS project_limit_unlocked boolean NOT NULL DEFAULT false,
              ADD COLUMN IF NOT EXISTS willing_to_pay boolean,
              ADD COLUMN IF NOT EXISTS project_limit_feedback text;
            ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
        """))

        # Policies
        session.exec(text("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can read components') THEN
                    CREATE POLICY "Anyone can read components"
                      ON public.components FOR SELECT TO authenticated USING (true);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can read pins') THEN
                    CREATE POLICY "Anyone can read pins"
                      ON public.pins FOR SELECT TO authenticated USING (true);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own projects') THEN
                    CREATE POLICY "Users can manage their own projects"
                      ON public.projects FOR ALL TO authenticated
                      USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage components of their own projects') THEN
                    CREATE POLICY "Users can manage components of their own projects"
                      ON public.project_components FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_components.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_components.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage connections of their own projects') THEN
                    CREATE POLICY "Users can manage connections of their own projects"
                      ON public.project_connections FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_connections.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = project_connections.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage code files of their own projects') THEN
                    CREATE POLICY "Users can manage code files of their own projects"
                      ON public.code_files FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = code_files.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = code_files.project_id AND projects.user_id = auth.uid()));
                END IF;

                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage conversations of their own projects') THEN
                    CREATE POLICY "Users can manage conversations of their own projects"
                      ON public.conversations FOR ALL TO authenticated
                      USING (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = conversations.project_id AND projects.user_id = auth.uid()))
                      WITH CHECK (EXISTS (SELECT 1 FROM public.projects WHERE projects.id = conversations.project_id AND projects.user_id = auth.uid()));
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert their own AI usage') THEN
                    CREATE POLICY "Users can insert their own AI usage" ON public.ai_usage
                      FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can read their own AI usage') THEN
                    CREATE POLICY "Users can read their own AI usage" ON public.ai_usage
                      FOR SELECT TO authenticated USING (auth.uid() = user_id);
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can manage their own onboarding profile') THEN
                    CREATE POLICY "Users can manage their own onboarding profile" ON public.user_profiles
                      FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
                END IF;
            END $$;
        """))
        session.commit()
    yield
