-- Completed AI request analytics used by the administrator dashboard.
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint references public.projects(id) on delete set null,
  provider text not null default '', model text not null default '', request_type text not null default '',
  input_tokens integer not null default 0, output_tokens integer not null default 0,
  total_tokens integer not null default 0, created_at timestamptz not null default now()
);
create index if not exists ai_usage_user_created_idx on public.ai_usage(user_id, created_at desc);
create index if not exists ai_usage_created_idx on public.ai_usage(created_at desc);
alter table public.ai_usage enable row level security;
create policy "Users can insert their own AI usage" on public.ai_usage for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can read their own AI usage" on public.ai_usage for select to authenticated using (auth.uid() = user_id);
