-- Complete application-data ownership and catalogue access rules.

create table if not exists public.conversations (
    id bigint generated by default as identity primary key,
    project_id bigint not null unique
      references public.projects (id) on delete cascade,
    history jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.project_components enable row level security;
alter table public.project_connections enable row level security;
alter table public.code_files enable row level security;
alter table public.conversations enable row level security;
alter table public.components enable row level security;
alter table public.pins enable row level security;

drop policy if exists "Users can manage their own projects" on public.projects;
create policy "Users can manage their own projects"
  on public.projects for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage components of their own projects"
  on public.project_components;
create policy "Users can manage components of their own projects"
  on public.project_components for all to authenticated
  using (exists (
    select 1 from public.projects
    where projects.id = project_components.project_id
      and projects.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.projects
    where projects.id = project_components.project_id
      and projects.user_id = auth.uid()
  ));

drop policy if exists "Users can manage connections of their own projects"
  on public.project_connections;
create policy "Users can manage connections of their own projects"
  on public.project_connections for all to authenticated
  using (exists (
    select 1 from public.projects
    where projects.id = project_connections.project_id
      and projects.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.projects
    where projects.id = project_connections.project_id
      and projects.user_id = auth.uid()
  ));

drop policy if exists "Users can manage code files of their own projects"
  on public.code_files;
create policy "Users can manage code files of their own projects"
  on public.code_files for all to authenticated
  using (exists (
    select 1 from public.projects
    where projects.id = code_files.project_id
      and projects.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.projects
    where projects.id = code_files.project_id
      and projects.user_id = auth.uid()
  ));

drop policy if exists "Users can manage conversations of their own projects"
  on public.conversations;
create policy "Users can manage conversations of their own projects"
  on public.conversations for all to authenticated
  using (exists (
    select 1 from public.projects
    where projects.id = conversations.project_id
      and projects.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.projects
    where projects.id = conversations.project_id
      and projects.user_id = auth.uid()
  ));

drop policy if exists "Anyone can read components" on public.components;
drop policy if exists "Public can read components" on public.components;
create policy "Public can read components"
  on public.components for select to anon, authenticated using (true);

drop policy if exists "Anyone can read pins" on public.pins;
drop policy if exists "Public can read pins" on public.pins;
create policy "Public can read pins"
  on public.pins for select to anon, authenticated using (true);

revoke insert, update, delete, truncate, references, trigger
  on public.components, public.pins from anon, authenticated;
grant select on public.components, public.pins to anon, authenticated;
